/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_myproj_TestClass */

#ifndef _Included_test_myproj_TestClass
#define _Included_test_myproj_TestClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_myproj_TestClass
 * Method:    getStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_test_myproj_TestClass_getStr
  (JNIEnv *, jobject);

/*
 * Class:     test_myproj_TestClass
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test_myproj_TestClass_initialize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
